services:
  app:
    build: .
    container_name: plant_lab_app
    restart: always
    env_file: .env.local
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_URL: "http://localhost:3000"
      NODE_ENV: "production"

  prisma-studio:
    build: .
    container_name: plant_lab_prisma
    env_file: .env.local
    ports:
      - "5555:5555"
    command: npm exec prisma studio -- --port 5555 --hostname 0.0.0.0 --browser none
    environment:
      NEXTAUTH_URL: "http://localhost:3000"
      NODE_ENV: "development"
